require:
  - rubocop-faker
  - rubocop-i18n
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  # RuboCop has a bunch of cops enabled by default. This setting tells RuboCop
  # to ignore them, so only the ones explicitly set in this file are enabled.
  NewCops: enable
  TargetRubyVersion: 2.7
  DisabledByDefault: false
  SuggestExtensions: false
  Exclude:
    - "db/schema.rb"
    - "**/tmp/**/*"
    - "**/templates/**/*"
    - "**/vendor/**/*"
    - "actionpack/lib/action_dispatch/journey/parser.rb"
    - "actionmailbox/test/dummy/**/*"
    - "actiontext/test/dummy/**/*"
    - "**/node_modules/**/*"

# Reativar!
Lint/UselessAssignment:
  Enabled: false # TODO: ativar posteriormente

# Layout Cops

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true
  EnforcedStyle: only_before

# Method definitions after `private` or `protected` isolated calls need one
# extra level of indentation.
Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods

# Use `foo { bar }` not `foo {bar}`.
Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyleForEmptyBraces: space

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_first_argument

Layout/ArrayAlignment:
  Enabled: true
  EnforcedStyle: with_first_element

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
  IndentationWidth: 2

Layout/BlockAlignment:
  Enabled: true
  EnforcedStyleAlignWith: either

Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: case

# RSpec Cops

# warning: its raising fake false warning
RSpec/FilePath:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: true
  Strict: true
  EnforcedStyle: inflected

RSpec/ReturnFromStub:
  Enabled: true
  EnforcedStyle: block


RSpec/VariableDefinition:
  Enabled: true
  EnforcedStyle: symbols

RSpec/VariableName:
  Enabled: true
  EnforcedStyle: snake_case

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

# Style Cops

Style/FormatStringToken:
  Enabled: false

# Helps you transition from mutable string literals to frozen string literals.
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
  Exclude:
    - "actionview/test/**/*.builder"
    - "actionview/test/**/*.ruby"
    - "actionpack/test/**/*.builder"
    - "actionpack/test/**/*.ruby"
    - "activestorage/db/migrate/**/*.rb"
    - "activestorage/db/update_migrate/**/*.rb"
    - "actionmailbox/db/migrate/**/*.rb"
    - "actiontext/db/migrate/**/*.rb"

# Prefer &&/|| over and/or.
Style/AndOr:
  Enabled: true
  EnforcedStyle: always

# Use Ruby >= 1.9 syntax for hashes. Prefer { a: :b } over { :a => :b }.
Style/HashSyntax:
  Enabled: true
  EnforcedStyle: no_mixed_keys
  EnforcedShorthandSyntax: never

# Check quotes usage according to lint rule below.
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

# Checks for redundant return expressions.
Style/RedundantReturn:
  Enabled: true
  AllowMultipleReturnValues: true # allows "return x, y"

Style/ClassAndModuleChildren:
  Enabled: false

Style/Semicolon:
  Enabled: true
  AllowAsExpressionSeparator: true

# I18n

I18n/RailsI18n:
  Enabled: true
I18n/GetText:
  Enabled: false
