name: Deploy Production
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  Deploying:
    uses: Quasar-Flash/workflow-dpl-action/.github/workflows/deployment-ruby-package.yml@dev
    with:
      release: true
    secrets: inherit
